### ISSUE TITLE
index out of range

### ISSUE THREAD

**Issue by xiaoshuai** [XiaoMi/soar#10]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

```
cat proc_active_device_addnew_detail.sql | soar
```

2. What did you expect to see?

3. What did you see instead?

```
panic: runtime error: index out of range

goroutine 1 [running]:
github.com/XiaoMi/soar/advisor.(*Query4Audit).RuleImplicitAlias(0xc4202bc900, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/zhangliang3/workspace/go/src/github.com/XiaoMi/soar/advisor/heuristic.go:47 +0x219
main.main()
        /home/zhangliang3/workspace/go/src/github.com/XiaoMi/soar/cmd/soar/soar.go:264 +0xc36

```

4. What version of are you using (`soar -version`)?

```
0.8.0
```

**Comment by martianzhang** [comment]
at advisor/heuristic.go:47 there is an uncheck list access, which raises this panic.

Can you show your SQLs in proc_active_device_addnew_detail.sql file?
