### ISSUE TITLE
mysql version

### ISSUE THREAD

**Issue by wusphinx** [XiaoMi/soar#101]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
mysql version is below:
```
+-----------------+
| @@version       |
+-----------------+
| 5.6.21-70.1-log |
+-----------------+
```

2. What did you expect to see?
the method`Version()` in `soar/database/mysql.go` will return `562`
But I think the version may be `5621` according to the rules

3. What did you see instead?
`5621` may be better, but I think the version should be `"5.6.21"` as string instead of `562` or `5621` as integer.

4. What version of are you using (`soar -version`)?
0.9.0

**Comment by martianzhang** [comment]
Agree with you, but may be not string, we will make it more compatible with MySQL comment version hint. 

MariaDB, Percona, MySQL Community all these editions should be checked.

```sql
select /*! 400000 1, */ 1;
```
