### ISSUE TITLE
生产环境与开发环境数据同步问题

### ISSUE THREAD

**Issue by shanyuxiyun** [XiaoMi/soar#105]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [SOAR Doc](http://github.com/XiaoMi/soar/blob/master/README.md)
- Any other questions can be asked in the community [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/xiaomi-dba/soar)

1. 在做SQL语句优化建议的时候，是否结合了MySQL Server的运行时信息去决策？
    如根据索引的使用情况、表行数大小、历史SQL执行耗时等MySQL服务端收集的信息
2. 如果【问题1】是yes，那么大部分情况下，开发环境的数据量及SQL执行情况与生产环境相差很大，系统是否有功能把现网的运行时数据同步到开发环境？
3. 如果【问题2】是yes，那么基本生产环境与开发环境网络是隔离的，生产环境的运行数据信息如何同步到开发环境？

谢谢。

**Comment by liipx** [comment]
1. 在配置了MySQL环境的情况下（online-dsn和test-dsn）回答是yes。建议中会包含SQL语句的EXPLAIN信息。
2. SOAR中含有数据采样功能呢，随机抽样算法具体实现可以[点这里](https://github.com/XiaoMi/soar/blob/0283009fcfe08c3d4937a63f692899039e844e85/database/sampling.go#L51)。
3. SOAR会在test-dsn中创建一个以`optimizer_`开头的临时数据库，将SQL中用到的库表结构同步到测试环境中，然后再进行数据采样。

您可以加入QQ群(758940447)或使用[gitter](https://gitter.im/xiaomi-dba/soar)来提问，我们能更快的响应解答。
