### ISSUE TITLE
-test-dsn配置

### ISSUE THREAD

**Issue by Linkyang953** [XiaoMi/soar#106]
请问配置文件中关于test-dsn的配置，端口号是可以自己随意指定吗，另外schema、user、password和online-dsn中的对应参数需要一样吗

test-dsn:
  addr: ""
  schema: information_schema
  user: ""
  password: '********'
  charset: utf8mb4
  disable: true

**Comment by ywc953** [comment]
另外配置了/etc/soar.yaml如何生效呢，配置了之后打印soar -print-config发现配置信息并没有更改？

**Comment by martianzhang** [comment]
请执行如下三个命令并反馈输出结果。
`soar -version`
`soar -print-config`
`soar -check-config`

**Comment by ywc953** [comment]
soar -version
Version: 2018-11-15 11:21:02 +0800 0.9.0-11-gea0ed2c
Branch: master
Compile: 2018-11-15 16:13:37 +0800 by go version go1.11 linux/amd64
GitDirty: 15

soar -print-config
online-dsn:
  addr: ""
  schema: information_schema
  user: ""
  password: '********'
  charset: utf8mb4
  disable: true
test-dsn:
  addr: ""
  schema: information_schema
  user: ""
  password: '********'
  charset: utf8mb4
  disable: true
allow-online-as-test: false
drop-test-temporary: true
cleanup-test-database: false
only-syntax-check: false
sampling-statistic-target: 100
sampling: false
profiling: false
trace: false
explain: true
conn-time-out: 3
query-time-out: 30
delimiter: ;
log-level: 3
log-output: /dev/stderr
report-type: markdown
report-css: ""
report-javascript: ""
report-title: SQL优化分析报告
markdown-extensions: 94
markdown-html-flags: 0
ignore-rules:
- COL.011
rewrite-rules:
- delimiter
- orderbynull
- groupbyconst
- dmlorderby
- having
- star2columns
- insertcolumns
- distinctstar
blacklist: ""
max-join-table-count: 5
max-group-by-cols-count: 5
max-distinct-count: 5
max-index-cols-count: 5
max-total-rows: 9999999
max-query-cost: 9999
spaghetti-query-length: 2048
allow-drop-index: false
max-in-count: 10
max-index-bytes-percolumn: 767
max-index-bytes: 3072
table-allow-charsets:
- utf8
- utf8mb4
table-allow-engines:
- innodb
max-index-count: 10
max-column-count: 40
index-prefix: idx_
unique-key-prefix: uk_
max-subquery-depth: 5
max-varchar-length: 1024
explain-sql-report-type: pretty
explain-type: extended
explain-format: traditional
explain-warn-select-type:
- ""
explain-warn-access-type:
- ALL
explain-max-keys: 3
explain-min-keys: 0
explain-max-rows: 10000
explain-warn-extra:
- Using temporary
- Using filesort
explain-max-filtered: 100
explain-warn-scalability:
- O(n)
show-warnings: false
show-last-query-cost: false
query: ""
list-heuristic-rules: false
list-rewrite-rules: false
list-test-sqls: false
list-report-types: false
verbose: false
dry-run: true
max-pretty-sql-length: 1024

soar -check-config
无输出

**Comment by martianzhang** [comment]
从`GitDirty: 15`上看你的代码是有修改过的，不是在release中下载的版本。

配置文件的加载顺序如下：
![2018-11-19 11 36 27](https://user-images.githubusercontent.com/1827047/48717270-0465f980-ec54-11e8-9677-10dc0cf250f3.png)

可以添加如下Debug信息，然后调高`-log-level 7`查看具体加载了哪个配置文件。
```go
diff --git a/common/config.go b/common/config.go
index f794857..1b2b134 100644
--- a/common/config.go
+++ b/common/config.go
@@ -700,6 +700,7 @@ func ParseConfig(configFile string) error {
                        if err != nil {
                                Log.Error("ParseConfig Config.readConfigFile Error: %v", err)
                        }
+                       Log.Debug("ParseConfig use config file: %s", config)
                        break
                }
        }
```

**Comment by ywc953** [comment]
我是用源码的方式安装，具体代码并没有改过，配置文件中所有参数必须齐全吗？可以只放改动的一部分吗？

**Comment by ywc953** [comment]
已配置成功，多谢啦！
