### ISSUE TITLE
echo "select  *  from szgb_user where  user_img like "http%" order by rand() limit 100" | ./soar -log-output=soar.log

### ISSUE THREAD

**Issue by MRchenao** [XiaoMi/soar#108]
针对  模糊匹配报告语法错误：

**## MySQL执行出错

syntax error at position 59 near 'order'
**
但是实际上这个sql语法是没有问题的。

**Comment by martianzhang** [comment]
![image](https://user-images.githubusercontent.com/1827047/48754689-85ada280-eccd-11e8-8a89-b1f5253a58d0.png)

在文件中评审SQL无法复现您反馈的这个问题。

请注意您在"http%"使用了双引号，而SQL外面也是用双引号包裹的。

**Comment by MRchenao** [comment]
确实是双引号的问题，感谢您的解答，把双引号变成单引号后就不报错了
