### ISSUE TITLE
SQL语句中存在注释, 解析存在问题

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#116]
原SQL语句:
```sql
select
*
-- comment
from tb
where col = 1;
```
结果: 
# Query: 1E82204137DA4CA4

★ ★ ★ ★ ☆ 95分

```sql

SELECT  
  *
```

##  不建议使用SELECT * 类型查询

* **Item:**  COL.001

* **Severity:**  L1

* **Content:**  当表结构变更时，使用\*通配符选择所有列将导致查询的含义和行为会发生更改，可能导致查询返回更多的数据。

# Query: 12FBD9CEB5E1C0D9

★ ★ ★ ★ ★ 100分

```sql

FROM  
  tb
 
WHERE  
  col  = 1
```

**Comment by martianzhang** [comment]
```sql
select * from
-- comment
tb;
select col from tb where col = 1;
```

two SQLs merge into one
