### ISSUE TITLE
sql 嵌套注释存在解析错误

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#117]
原 sql 语句:
```sql
SELECT 
  * 
FROM 
/*
  注释1
   /*
  注释2
  */ 
*/
`db`
```
 
返回结果:
# Query: CE2B7427716C1CE9

★ ★ ★ ★ ★ 100分

```sql

SELECT  
  * 
FROM  
  */ `db`
```

**Comment by martianzhang** [comment]
看来github markdown对注释套注释的渲染也存在一些问题 😁 

这个问题我来调一下SplitStatement函数，多谢 @xiyangxixian

**Comment by martianzhang** [comment]
```sql
/*
  注释1
   /*
  注释2
  */ 
*/
```

SQL中多行注释嵌套MySQL语法是不支持的，遇到第一个`  */ `立即结束注释。

这里不应该给OK的建议，需要给出语法报错。截止当前最新版本 a4a641a6f7f8cac07785405f515ccd71bd78a5e2 已经能给出语法错误的建议了。
