### ISSUE TITLE
未来对tidb的支持

### ISSUE THREAD

**Issue by Freyayan** [XiaoMi/soar#129]
1.因为目前parser就是tidb的parser，所以是否可以支持tidb的智能优化
2.tidb是兼容mysql 的，所以协议方面应该是可以的。

**Comment by martianzhang** [comment]
请列举SOAR还不支持的 TiDB SQL 优化的案例，SOAR现在提供的启发式建议和索引优化建议很多是不区分数据库类型的。

**Comment by martianzhang** [comment]
long time no feedback. If you need help please reopen this issue again.
