### ISSUE TITLE
blingbling add get metadata feature

### ISSUE THREAD

**Issue by daiguadaidai** [XiaoMi/soar#134]
[https://github.com/daiguadaidai/blingbling#获取元数据](https://github.com/daiguadaidai/blingbling#%E8%8E%B7%E5%8F%96%E5%85%83%E6%95%B0%E6%8D%AE)

**Comment by martianzhang** [comment]
Following command will give AST info, but not JSON format.
```bash
soar -query file.sql -report-type ast
soar -query file.sql -report-type tias
```
AST support JSON format may be more useful for other program.

Add `-report-type=ast-json` for vitess parser or `-report-type=tiast-json` for pingcap parser

**Comment by martianzhang** [comment]
Complicate SQL print all AST info will give a large JSON. We should consider more cases for this issue.

**Comment by martianzhang** [comment]
b237d5e support AST json print
