### ISSUE TITLE
Args format error

### ISSUE THREAD

**Issue by ywc953** [XiaoMi/soar#138]
输入soar -online-dsn "admin:admin@127.0.0.1:41880/testdb"命令会报错：
Args format error，use --help see how to use it
输入soar -config "XXXX"设置配置文件路径也会报相同错误
请问是我命令格式有错吗

**Comment by liipx** [comment]
必须指定 `-query`

**Comment by ywc953** [comment]
也就说是这种参数指定方法只在当次生效吗 @liipx
