### ISSUE TITLE
第三方包依赖

### ISSUE THREAD

**Issue by ywc953** [XiaoMi/soar#139]
你好，之前 @martianzhang 回复说
 we have update github.com/pingcap/parser, now soar can be built with no other third-party source code dependency.

我只下载soar源码编译也可以连接mysql数据库了，但我在最新代码github.com/XiaoMi/soar/database/mysql.go文件中看到
![image](https://user-images.githubusercontent.com/44738008/49271832-47bd3500-f4aa-11e8-9806-7f3e37b9f8dd.png)

"github.com/ziutek/mymysql/mysql"
 _ "github.com/ziutek/mymysql/native"
 "vitess.io/vitess/go/vt/sqlparser"
这三个包还需要吗

**Comment by martianzhang** [comment]
我写这句的意思是已经把这些第三方包依赖的问题通过vendor的方式管理起来了。
不需要再下载联网下载第三方包，使用还是会使用。

**Comment by benbenlis** [comment]
你好，我下载了soar的源码，在windows下编译时报如下错误，请问怎样解决，谢谢啦

![image](https://user-images.githubusercontent.com/13809863/63561209-ab811400-c58b-11e9-80da-e344ad235c9d.png)
![image](https://user-images.githubusercontent.com/13809863/63561226-c05da780-c58b-11e9-9d13-09c53b7db1d3.png)
