### ISSUE TITLE
mac 上无法执行：cannot execute binary file

### ISSUE THREAD

**Issue by xyzwps** [XiaoMi/soar#14]
我在 mac 上按安装赋权后，无法执行

```
$ wget https://github.com/XiaoMi/soar/releases/download/v0.8.0/soar.linux-amd64 -O soar

$ chmod a+x soar

$ sudo echo 'select * from film' | ./soar
-bash: ./soar: cannot execute binary file

```

mac 版本：MacBook Pro (Retina, 15-inch, Mid 2015)

**Comment by martianzhang** [comment]
@xyzwps mac show download file which `darwin`.

**Comment by Sungq1990** [comment]
wget https://github.com/XiaoMi/soar/releases/download/v0.8.0/soar.darwin-amd64 -O soar
chmod a+x soar

**Comment by lgyers** [comment]
安装完，执行
[soar.go:105] ioutil.ReadAll Error: read /dev/stdin: resource temporarily unavailable
