### ISSUE TITLE
参数比较包含隐式转换有问题

### ISSUE THREAD

**Issue by saigu** [XiaoMi/soar#151]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
分析select * from A where deleted = 1 limit 100
deleted 为bit(1)

2. What did you expect to see?
能走索引

3. What did you see instead?
分析报告给出 参数包含隐式转换，无法使用索引
Item: ARG.003
Severity: L4
Content: brandgood.deleted definition is bit(1) not int

4. What version of are you using (`soar -version`)?
0.10.0

**Comment by martianzhang** [comment]
```sql
SELECT * FROM sakila.film WHERE rental_rate > 1
```
also need fix DECIMAL compare with INTEGER
