### ISSUE TITLE
线上环境、测试环境版本获取

### ISSUE THREAD

**Issue by ywc953** [XiaoMi/soar#157]
你好，在env.go代码中为何线上环境和测试环境的版本获取都是通过vEnv.Version()？
![image](https://user-images.githubusercontent.com/44738008/49784068-043eb280-fd57-11e8-9597-0e7bda05550a.png)
![image](https://user-images.githubusercontent.com/44738008/49784083-13256500-fd57-11e8-9a4e-46aeef1ed20b.png)

线上版本为何不是通过conn.Version()?

**Comment by martianzhang** [comment]
笔误，打错了 🤦‍♂️
