### ISSUE TITLE
通过命令行配置 -test-dsn参数时，无法正确解析密码含有'@','!'符号的MySQL串

### ISSUE THREAD

**Issue by iodherror** [XiaoMi/soar#16]
mysql串密码带有!会直接报错。
![image](https://user-images.githubusercontent.com/20450030/47284064-72e57680-d618-11e8-8f0d-44245986a89d.png)
![image](https://user-images.githubusercontent.com/20450030/47284070-77aa2a80-d618-11e8-9211-471b65f26d51.png)

带有@号时会解析错误。
![image](https://user-images.githubusercontent.com/20450030/47284075-809afc00-d618-11e8-83ce-6f98f3dfde92.png)
![image](https://user-images.githubusercontent.com/20450030/47284088-8e508180-d618-11e8-972f-549737faa559.png)

**Comment by martianzhang** [comment]
账号密码中如包含特殊符号可在配置文件中设置。命令行使用的DSN格式先天对特殊字符不友好。yaml配置没有这类问题。我们会在文档中进一步说明

**Comment by wangmin19861205** [comment]
配置成文件还是存在该问题
![image](https://user-images.githubusercontent.com/7638971/47838157-78497a80-dde9-11e8-81c3-64e9fcfd129d.png)
![image](https://user-images.githubusercontent.com/7638971/47838188-8f886800-dde9-11e8-943f-7bb3d9ae36e6.png)

**Comment by iodherror** [comment]
我这使用配置文件也一样有问题。
看了下代码，这个是config.go里面的逻辑有问题导致的。
可以自己先简单修正一下。
