### ISSUE TITLE
go-sql-driver与mymysql的选择

### ISSUE THREAD

**Issue by ywc953** [XiaoMi/soar#161]
你好，看到目前soar master分支用的是ziutek的mymysql包，go-sql-driver分支用的是go-sql-driver包，请问贵司有对比过两个包的性能吗，从长期来说soar会选择哪个包作为主要分支的依赖包呢？

**Comment by martianzhang** [comment]
准备放弃mymysql依赖迁移至go-sql-driver，从社区的维护情况看go-sql-driver目前更好一点。

**Comment by wowdba** [comment]
迁移到go-sql-driver后，超时参数新增了Timeout，ReadTimeout  ,WriteTimeout 。但是设置后不生效。
