### ISSUE TITLE
可否基于指定不同类型数据库进行分析

### ISSUE THREAD

**Issue by gshome** [XiaoMi/soar#162]
后续是否有想法梳理个基于不同数据库类型client去匹配分析，比如在安装有db2 client的环境，配置db2连接信息，就可以调client目录下的lib包等来获取相应API实现分析db2语法及执行计划，只是一个想法，不知道哪位大佬有类似的想法

**Comment by martianzhang** [comment]
未来一年内这边不会寻求对DB2, Oracle, SQL Server，PostgreSQL等其他数据库产品的支持。

长期计划可以请和同行们交流。
