### ISSUE TITLE
sql执行计划扫描行数超过 设定的阈值explain-max-rows: 5000  没有给出提示

### ISSUE THREAD

**Issue by himura-kenshin** [XiaoMi/soar#168]
[](url)
![image](https://user-images.githubusercontent.com/24806747/50075053-c63f0400-0218-11e9-811e-c632c88715f4.png)

4. What version of are you using (`soar -version`)?

0.9.0

**Comment by martianzhang** [comment]
红圈的内容就是提示了，'**' 是markdown加粗字体的语法，前面还有一个骷髅头。 👅

**Comment by himura-kenshin** [comment]
哦哦  这个索引比较低效  可以 让 soar 生成高效索引 输出吗？

**Comment by himura-kenshin** [comment]
就像美团SQLAdvisor  一样 直接给出最优的索引建议

**Comment by martianzhang** [comment]
@himura-kenshin 请提供一个查询SQL和建表语句，截图中并没有需要优化的SQL语句。

**Comment by himura-kenshin** [comment]
哦哦  ，好的 了解
