### ISSUE TITLE
"insert" syntax check bug

### ISSUE THREAD

**Issue by hongjin95** [XiaoMi/soar#170]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
echo 'insert into tb values(1)' | soar -only-syntax-check

2. What did you expect to see?
Result of syntax check

3. What did you see instead?
Bug report of soar.

4. What version of are you using (`soar -version`)?
the latest.

**Comment by martianzhang** [comment]
@hongjin95  ref #90
