### ISSUE TITLE
复杂查询的连等建议的支持

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#173]
![qq 20181223142512](https://user-images.githubusercontent.com/19143559/50381316-c9297100-06be-11e9-8335-019f6ed58ba5.png)

**Comment by martianzhang** [comment]
We need to add a `walk` or `find` function with `pingcap/parser`.
now only check the first equation, so the following condition will not give suggest
```sql
WHERE col = col = '' and col1 = 'xx'
```
