### ISSUE TITLE
采样算法希望可以优化一下

### ISSUE THREAD

**Issue by sylzd** [XiaoMi/soar#174]
#### Feature Description

在大表中进行随机采样较慢，希望能增加一些如顺序采样、分段采样等方式供选择，提高在大表中进行采样的性能并适应不同的应用场景。

#### Use Case(s)

对数据随机性要求较低，但是表较大时比较有用。

**Comment by martianzhang** [comment]
62f0b8eb30353d53654838237c99b4bef412ba1e

we add a new sampling config
`sampling-condition`

Example:
```bash
-sampling-condition="LIMIT 100"
-sampling-condition="WHERE id % 100 = 5"
```
