### ISSUE TITLE
「不要使用hint，如sql_no_cache，force index，ignore key，straight join等」例子不对

### ISSUE THREAD

**Issue by Chyroc** [XiaoMi/soar#18]
https://github.com/XiaoMi/soar/blob/master/doc/heuristic.md 中的「不要使用hint，如sql_no_cache，force index，ignore key，straight join等」例子不对

![image](https://user-images.githubusercontent.com/15604894/47287830-2bfe7d80-d626-11e8-9f28-a27f50c915de.png)

**Comment by martianzhang** [comment]
SQL_NO_CACHE, STRAIGHT_JOIN check add TODO
