### ISSUE TITLE
DataFree overflows int

### ISSUE THREAD

**Issue by LiJunWei** [XiaoMi/soar#184]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

[E] [show.go:110] recover ShowTableStatus()%!(EXTRA *strconv.NumError=strconv.Atoi: parsing "18446744055523987336": value out of range)

2. What did you expect to see?
大表Data_free值特别大超过int类型数值上限的情况可以正常执行

3. What did you see instead?

4. What version of are you using (`soar -version`)?
0.9.0

**Comment by martianzhang** [comment]
0.9.0 soar use mymysql, but now(0.10+) soar use go-sql-driver for MySQL driver. strconv.Atoi is not used now.

As #185 mentioned, DataFree's datatype needs to change to uint64, and other table status int type field.
