### ISSUE TITLE
为什么会创建库表还用DDL语句???好恐怖

### ISSUE THREAD

**Issue by 564064202** [XiaoMi/soar#191]
createTable, test_table DDL Error : dial tcp: i/o timeout

还有就是optimizer_190115144402_JsJN8Yp84uMgbeqF这样的表是用来干啥的.

还有为啥有查询字段没有索引,也没有给出反馈

**Comment by martianzhang** [comment]
建议先看一下文件中关于测试环境的描述，SOAR会在测试环境中把线上环境的库表建出来。
