### ISSUE TITLE
有索引的还会提示加索引

### ISSUE THREAD

**Issue by Jetereting** [XiaoMi/soar#195]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.
1.已有索引的还是提示加索引
2.有的不适合加索引，比如状态，可能整个表里就两个不同的

2. What did you expect to see?
1.已有索引的不提示
2.有的不适合加索引的不提示

3. What did you see instead?

4. What version of are you using (`soar -version`)?
Version: 2019-01-21 16:54:09 +0800 0.11.0-16-gc12ae96
Branch: master
Compile: 2019-01-29 15:08:30 +0800 by go version go1.11.4 linux/amd64
GitDirty: 0

**Comment by martianzhang** [comment]
@Jetereting  请提供复现测试用的表结构和SQL语句。

**Comment by Jetereting** [comment]
1.的情况已经没有了，应该是我数据库配置的问题
2.可以通过散粒度判断和筛选
