### ISSUE TITLE
Cant handle Create TEMPORAEY

### ISSUE THREAD

**Issue by lolspider** [XiaoMi/soar#203]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

>soar -query 1.sql -only-syntax-check
At SQL 1 : line 1 column 16 near "CREATE TEMPORARY TABLE IF NOT EXISTS table2 AS (SELECT * FROM table1)" (total length 69)

2. What did you expect to see?
i want to handle create temporary correctly.

3. What did you see instead?

i get an error.

4. What version of are you using (`soar -version`)?

>soar -version
Version: 2019-01-21 16:54:09 +0800 0.11.0-16-gc12ae96
Branch: master
Compile: 2019-02-18 16:14:56 +0800 by go version go1.11.5 darwin/amd64
GitDirty: 0

**Comment by martianzhang** [comment]
soar use pingcap/parser as it's SQL parser, create temporary is not supported yet.

![image](https://user-images.githubusercontent.com/1827047/58320433-34ce6080-7e4e-11e9-9acb-a6214b857cc6.png)

**Comment by martianzhang** [comment]
Related Issue: https://github.com/pingcap/parser/issues/52

**Comment by martianzhang** [comment]
pingcap/parser has supported `create temporary table` syntax
