### ISSUE TITLE
连接数据库优化建议

### ISSUE THREAD

**Issue by yangjiuyi** [XiaoMi/soar#204]
当前连接数据库的优化建议，除了分析explain结果，只是针对当前的表结构添加索引建议；
可否根据表的数据量，字段的数据分布，SQL执行频率等来提出更合理的建议呢

**Comment by martianzhang** [comment]
1. 表的数据量 [SUPPORTED]
2. 字段的数据分布 [SUPPORTED]
3. SQL 执行频率 [WILL NOT]
