### ISSUE TITLE
parse -ast-json error

### ISSUE THREAD

**Issue by oillamp** [XiaoMi/soar#208]
Please answer these questions before submitting your issue. Thanks!

**INTPUT**
```
echo 'UPDATE `xxx` SET aaa="a;" WHERE `id` = 15;' | ~/Downloads/soar.darwin-amd64 -report-type ast-json
```

**OUTPUT**
```
```

**VERSION**
Version: 2019-04-16 11:42:51 +0800 0.11.0-43-gc2299c3
Branch: dev
Compile: 2019-04-16 11:49:55 +0800 by go version go1.11.4 linux/amd64
GitDirty: 0

![image](https://user-images.githubusercontent.com/14213113/58446847-e3b3ba80-8134-11e9-92c0-5187d3660b90.png)

**Comment by martianzhang** [comment]
14c19f4d89c8cc635ae6370e5415a2bd1588e652 regression bug
