### ISSUE TITLE
语法检测时 如果sql语法错误$?也会返回0

### ISSUE THREAD

**Issue by EverCurse** [XiaoMi/soar#210]
1. What did you do?

[root@cloud-s-1 ~]# echo "select * frm tb" | soar -only-syntax-check
At SQL 1 : syntax error at position 13 near 'frm'

[root@cloud-s-1 ~]# echo $?
0

2. What did you expect to see?

$?返回非0状态

3. What did you see instead?

4. What version of are you using (`soar -version`)?
Version: 2018-11-10 22:56:14 +0800 @11f1bc3
Branch: master
Compile: 2018-11-10 22:58:08 +0800 by go version go1.10.4 linux/amd64
GitDirty: 0

**Comment by martianzhang** [comment]
使用最新的源码编译，如果语法报错 $? 返回值为非 0。

![image](https://user-images.githubusercontent.com/1827047/60569142-2bb3a600-9da1-11e9-95c9-03a66c199490.png)


![image](https://user-images.githubusercontent.com/1827047/60569007-e55e4700-9da0-11e9-94f3-a2d2cc802a46.png)
