### ISSUE TITLE
sql id 能做到由用户指定吗？

### ISSUE THREAD

**Issue by bruceauyeung** [XiaoMi/soar#211]
#### Feature Description

我看到代码里面sql id 是用md5来生成的，能做成支持由用户指定吗？比如说我输入
~~~
# id:myid
select * from table1 where col1=''
~~~
则生成的报告里面，query id 为 myid

#### Use Case(s)

用户程序从mybatis工程中抽取了sql语句，输出了
~~~
# java-method: a.b.Class1#method1
select * from table1 where col1=''
~~~
我希望报告中的query id为 a.b.Class1#method1
这样就方便用户把报告和java 方法进行关联。

**Comment by martianzhang** [comment]
可以支持输入一条 SQL 告诉你它对应的 ID 是什么，然后在 Java 中可以做一个关联映射解决用户自定义的问题。

![image](https://user-images.githubusercontent.com/1827047/60569764-ad580380-9da2-11e9-9734-36f9bb52cd05.png)

https://github.com/XiaoMi/soar/commit/aeb7868114fac4fecdba162d24ef36867fc0909c 增加了 ID 输出

**Comment by bruceauyeung** [comment]
这个方法解决不了我的场景啊，我从java工程中抽取出来的是一批sql。
ps：我已经按照我描述的那样实现了，先从sql注释中寻找id，如果没有找到再用md5生成。
