### ISSUE TITLE
单引号sql语句报错

### ISSUE THREAD

**Issue by brisk21** [XiaoMi/soar#216]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
echo $soar->score("SELECT * FROM `test_blog` where  title like '%php%'");

2. What did you expect to see?
SELECT  * FROM  `test_blog` where  title like '%php%'

3. What did you see instead?
SELECT  * FROM  `test_blog` where  title like %php%

4. What version of are you using (`soar -version`)?
The latest version

  return $this->exec("echo '$sql;' | $this->soarPath ".$this->getFormatConfig($this->config));

**Comment by martianzhang** [comment]
SQL 放在文件中 cat file.sql | soar 这种方式给 soar, 不然就需要自己的程序中做好转义。
