### ISSUE TITLE
mac系统下make报错了, go版本号1.12.7报错了

### ISSUE THREAD

**Issue by phpcs** [XiaoMi/soar#217]
**mac系统下make报错了, go版本号1.12.7报错了**

Go version check ...
go version check pass
Run gofmt on all source files ...
gofmt -l -s -w ...
/Users/mac/go/src/github.com/XiaoMi/soar/common/meta_test.go:65:59: expected '}', found ':'
/Users/mac/go/src/github.com/XiaoMi/soar/common/meta_test.go:106:59: expected '}', found ':'
make: *** [fmt] Error 2

**把go换成1.10版本也是同样错误**

**Comment by phpcs** [comment]
应该是个测试文件吧, 删除了就编译成功了!

**Comment by martianzhang** [comment]
@phpcs 
从报错信息看像是你的 `meta_test.go` 文件已经被修改过了，使用当前干净的代码测试并未出现语法问题。

```bash
go test -run TestGetDataBytes
PASS
ok  	github.com/XiaoMi/soar/common	0.003s
```
