### ISSUE TITLE
清理测试库异常

### ISSUE THREAD

**Issue by wangmin19861205** [XiaoMi/soar#223]
CleanUp failed Error: Received #1044 error from MySQL server: "Access denied for user 'userA'@'%' to database 'optimizer_190805160614_xfudpfwkoyrz1xbs'"

清理测试数据库异常，而且在配置文件中添加cleanup-test-database: true后无输出

**Comment by wangmin19861205** [comment]
而且感觉生成的临时数据库命名是不是有问题    这个数据库都几天前了  怎么还说不到一小时
CleanupTestDatabase by pass database optimizer_190806104138_kqidg0frlkkdsjzg, -0.99 less than 1 hours

**Comment by martianzhang** [comment]
从报错信息上看，为测试环境账号权限不足。
