### ISSUE TITLE
Windows环境下，cmd与powershell输出结果不一致

### ISSUE THREAD

**Issue by leslieeilsel** [XiaoMi/soar#225]
#### 测试环境
- Windows 10 教育版 1809
#### 测试脚本：
```shell
echo 'SELECT * FROM `fa_user` `user` LEFT JOIN `fa_user_group` `group` ON `user`.`group_id`=`group`.`id`;' | C:\Soar\soar.exe  -online-dsn=selectuser:123456@127.0.0.1:3306/database  -test-dsn=root:leslie@127.0.0.1:3306/ifengxi  -log-output=D:\Laravue\ifengxi\Backend\storage\logs\soar.log  -log-level=7  -report-type=json
```
#### CMD中执行结果：
![cmd](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/POYV*NgI5.eTDmtsZ8RUWc60AWHr.EH2CCJcakU.eRI!/r/dLYAAAAAAAAA)
#### PowerShell中执行结果：
![powershell](http://r.photo.store.qq.com/psb?/V12ol6gx2nrILn/oT0CxkvnfM1eXKRWvfHMlB..coUxqdQ.BfRJ46pgvwE!/r/dFQBAAAAAAAA)

### 同样的命令在不同的终端中执行结果不一样，PowerShell中是正确的结果。

**Comment by martianzhang** [comment]
建议把 SQL 及配置均方便在文件中。
*  配置文件可以通过 -config 参数指定
* SQL 可以通过 -query file.sql 指定
