### ISSUE TITLE
RES.005 规则太简单了，误报率高

### ISSUE THREAD

**Issue by bruceauyeung** [XiaoMi/soar#226]
这条规则是检查 update 的 set 中是否用了and而不是","
然而检查逻辑太简单，只是简单的对整个set表达式部分进行字符串包含检查，所以如果其中包含有多个查询条件的子查询，就会出错，比如：
`update table1 set a = ( select a from table2 where b=1 and c=2), b=1, c=2 where d=2`

**Comment by martianzhang** [comment]
针对反馈的这条 UPDATE 语句已经通过添加 switch case 进行了兼容。如果您还遇到了其他复杂的查询请求辛苦再帮忙反馈。这个 ISSUE 我先关闭了。
