### ISSUE TITLE
 install error undefined: sqlparser.SEQUENCE

### ISSUE THREAD

**Issue by yann0917** [XiaoMi/soar#228]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

install error 

源码安装错误
```shell
go get -d github.com/XiaoMi/soar
cd ${GOPATH}/src/github.com/XiaoMi/soar && make
```
```shell
Go version check ...
go version check pass
Run gofmt on all source files ...
gofmt -l -s -w ...
Building ...
# github.com/XiaoMi/soar/ast
ast/token.go:366:2: undefined: sqlparser.SEQUENCE
make: *** [build] Error 2
```
2. What did you expect to see?

install success

3. What did you see instead?

4. What version of are you using (`soar -version`)?

- go version 1.13
- MacOS 1.15 beta
- **Branch dev**

**Comment by martianzhang** [comment]
Thanks you!
I'll try with Go 1.13. We develop `soar` with Go 1.11.

**Comment by martianzhang** [comment]
![image](https://user-images.githubusercontent.com/1827047/64942860-c568fa80-d89c-11e9-8182-ad60a7f9d2b9.png)
