### ISSUE TITLE
SOAR目前只支持MySQL协议兼容的SQL评审，暂不支持其他数据库类型。

### ISSUE THREAD

**Issue by ayee1616166** [XiaoMi/soar#23]
Please search the existing issues for relevant feature requests,  add upvotes to pre-existing requests.
1.如何采用其他数据库进行sql验证
2.在采用postgres数据进行测试时候
         情况1：没有任何信息输出 ，其中指定的err日志没有任何报错提示
         情况2：只是打印结果，并无法确认是从内部mysql测试库测试得出的结论，还是其他库得出的结论；其中指定的err日志没有任何报错提示

**Comment by martianzhang** [comment]
目前只针对mysql语法族的SQL语句给优化建议，PostgreSQL或Oracle语法兼容性上会有问题。如果测试环境配置成了其他类型的数据库打印的日志和输出会有各种不可预期的情况。

SOAR在不连接数据库的时候给出的建议很多是数据库类型无关的通用型建议，您可以参考。后续也欢迎社区的朋友帮忙一起把PostgreSQL和Oracle的支持做起来。
