### ISSUE TITLE
 Install compatible go1.11

### ISSUE THREAD

**Issue by leobuzhi** [XiaoMi/soar#230]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
make

2. What did you expect to see?
build success

3. What did you see instead?
make: *** [build] Error 2

4. What version of are you using (`soar -version`)?

5. Detail info
The dev version of the doc write dependency is Go 1.10+(see also https://github.com/XiaoMi/soar/blob/dev/doc/install.md), which is actually go1.12+, because the -X parameter is added (go1.12 Only introduced), this will cause the following versions of go1.12 can not be compiled
Compatible with older versions and more info when build failed.

**Comment by martianzhang** [comment]
I will update doc, no more support old go version.
