### ISSUE TITLE
support dsn with ssh tunnel ?

### ISSUE THREAD

**Issue by somnus-L** [XiaoMi/soar#231]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [SOAR Doc](http://github.com/XiaoMi/soar/blob/master/README.md)
- Any other questions can be asked in the community [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/xiaomi-dba/soar)

**Comment by martianzhang** [comment]
SOAR now use `go-sql-driver/mysql` DSN format. 

https://github.com/go-sql-driver/mysql#dsn-data-source-name

What you mean about the ssh tunnel supported? @somnus-L

**Comment by somnus-L** [comment]
I mean when connecting to the database, sometimes in addition to the standard DSN, you also need ssh proxy, how to add ssh proxy in soar config.yaml

**Comment by martianzhang** [comment]
There many ways to create ssh tunnel for proxy. Google may help you, SOAR will not do this thing.

https://www.linode.com/docs/databases/mysql/create-an-ssh-tunnel-for-mysql-remote-access/
