### ISSUE TITLE
sql解析报错

### ISSUE THREAD

**Issue by WinnerSong** [XiaoMi/soar#235]
SELECT `id`, `name` FROM `user` WHERE 0=1 ORDER BY convert(name using gbk)
类似使用到 using gbk都会报执行错误
![image](https://user-images.githubusercontent.com/15809546/68097298-45046480-fef1-11e9-9c3a-53c16da53b6a.png)

**Comment by martianzhang** [comment]
confirm this bug

```bash
$ ./bin/soar -query 'SELECT CONVERT("abc" using gbk);'
# Query: 3D86D2020661079D

☆ ☆ ☆ ☆ ☆ 0分

SELECT  
  CONVERT( "abc" using  gbk)

## MySQL execute failed
[parser:1115]Unknown character set: 'gbk'
```
