### ISSUE TITLE
能否提供docker安装

### ISSUE THREAD

**Issue by ouwenfa2006** [XiaoMi/soar#239]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [SOAR Doc](http://github.com/XiaoMi/soar/blob/master/README.md)
- Any other questions can be asked in the community [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/xiaomi-dba/soar)

**Comment by martianzhang** [comment]
soar is just a command-line tool. you can use it in your Dockerfile as a binary as you wish.
