### ISSUE TITLE
没有界面？太丑了。应该加入UI界面。

### ISSUE THREAD

**Issue by stevenliuit** [XiaoMi/soar#24]
Please search the existing issues for relevant feature requests,  add upvotes to pre-existing requests.

#### Feature Description

应该加入UI界面。
改用JAVA或者Python这样看起来更好看。
整合apache监控系统生成报告。

#### Use Case(s)

无

**Comment by martianzhang** [comment]
丑我们认了，辛苦少侠帮忙一起做一个UI吧。

**Comment by stevenliuit** [comment]
哈哈

**Comment by martianzhang** [comment]
duplicate with #15
