### ISSUE TITLE
RemoveSQLComments 字符串转义引号后跟着的#号会替换错误

### ISSUE THREAD

**Issue by chrobin** [XiaoMi/soar#257]
https://github.com/XiaoMi/soar/blob/ee6cfd0c103c23961b9a68baf80a9976612f14a5/database/mysql.go#L260
RemoveSQLComments中如果SQL中的字符串带有#号，会被替换错误
如：
insert into tbl (id,a) values(1,'\'#a\'');

**Comment by martianzhang** [comment]
''a'' 您 SQL 中不写的不是双引号，是把单引号写了两遍。所以 #a 后面的内容会被替换掉。

**Comment by chrobin** [comment]
我上面的例子中的转义字符被github转义掉了，应该是：
insert into tbl (id,a) values(1,'\\'#a'\\');
这种会解析错误

**Comment by chrobin** [comment]
与#261中提到的应该是一个问题
