### ISSUE TITLE
索引前缀 在配置文件中 自定义后,advisor/rules.go中 的建议未使用全局配置里的值.

### ISSUE THREAD

**Issue by earl86** [XiaoMi/soar#266]
Please answer these questions before submitting your issue. Thanks!

在 soar.yml中定义  unique-key-prefix: uniq_
advisor/rules.go中 的建议 未使用全局配置里的值.
Content:  `建议普通二级索引以idx_为前缀，唯一索引以uk_为前缀。`,

**Comment by LonelyChick** [comment]
这个是因为只有检查的时候是按照配置文件中的配置的前缀来匹配的，如果不符合时输出的Content是写死的。

**Comment by martianzhang** [comment]
@LonelyChick Thanks report!
