### ISSUE TITLE
添加QQ群没反应，gitter交流群没人回复

### ISSUE THREAD

**Issue by edidada** [XiaoMi/soar#274]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [SOAR Doc](http://github.com/XiaoMi/soar/blob/master/README.md)
- Any other questions can be asked in the community [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/xiaomi-dba/soar)

**Comment by edidada** [comment]
现在（2021年2月）这个项目还有沟通渠道吗？

**Comment by shengminjie** [comment]
感觉没有沟通渠道了。但是还有dev在更新。

**Comment by martianzhang** [comment]
I will continue to commit codes to soar, but not full-time management.
Wish other XiaoMi coder can work together.
