### ISSUE TITLE
怎么-cleanup-test-database数据库

### ISSUE THREAD

**Issue by czxin788** [XiaoMi/soar#281]
soar -online-dsn="root:xxxxx@172,xxx,xxx,xx:3317/soar"  -cleanup-test-database
报错：
[root@xxx-jumpserver bin]# cat soar.log 
2021/05/09 19:04:13.407 [E] [mysql.go:95]  Error 1045: Access denied for user ''@'localhost' (using password: NO)
2021/05/09 19:04:13.407 [E] [env.go:157]  CleanupTestDatabase failed Error:dsn is disable

**Comment by LonelyChick** [comment]
TestDSN没有指定
