### ISSUE TITLE
yaml配置schema带有中划线，报错[mysql.go:95]  Error 1064

### ISSUE THREAD

**Issue by linjun666** [XiaoMi/soar#286]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
配置schema为school-sports-test

2. What did you expect to see?
给出explain报告和sql优化建议

3. What did you see instead?
没有explain报告

4. What version of are you using (`soar -version`)?
 2019-01-21 16:54:09 +0800 0.11.0-16-gc12ae96

**Comment by martianzhang** [comment]
duplicate with #252 , please upgrade your soar binary by new compiling
