### ISSUE TITLE
请问字段或表名不支持带"`"符号的语句吗？

### ISSUE THREAD

**Issue by rootrl** [XiaoMi/soar#33]
正常：
./soar -query "select id from users;"

提示语法错误：
./soar -query "select `id` from `users`;"

ORM中拼的SQL很多都是这种带"`"符号的

**Comment by liipx** [comment]
```
./soar -query "select \`id\` from \`users\`;"
```
在命令行中使用的时候请给'`'转义一下，建议复杂SQL放到SQL文件中，用 cat file | soar 的方式来评审，或者用-query指定文件路径。

**Comment by martianzhang** [comment]
./soar -query 'select `id` from `users`;'

把双引号改成单引号可以解决这个问题，另外命令行很多特殊字符都需要转义。建议把SQL写在文件中使用如下几种方式评审。

```
cat file.sql | soar

soar -query file.sql
```

**Comment by rootrl** [comment]
好的 感谢！
