### ISSUE TITLE
-query 既可以是sql语句也可以是文件路径

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#34]
Please search the existing issues for relevant feature requests,  add upvotes to pre-existing requests.

#### Feature Description

A written overview of the feature.

#### Use Case(s)

Any relevant use-cases that you see.

**Comment by Becivells** [comment]
确实没有注明很少有人知道这个用法
-query string
        Queries for analyzing
  -query-time-out int
        QueryTimeOut, 数据库SQL执行超时时间，单位秒 (default 30)

**Comment by martianzhang** [comment]
b80ed7f  updated
