### ISSUE TITLE
-report-type=text always get 100 score

### ISSUE THREAD

**Issue by 90wukai** [XiaoMi/soar#37]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
If possible, provide a recipe for reproducing the error.

![jietu20181024-162939](https://user-images.githubusercontent.com/27050941/47417334-54af8000-d7aa-11e8-8ad1-f963fa8879da.jpg)

2. What did you expect to see?

3. What did you see instead?

4. What version of are you using (`soar -version`)?

0.8.1

**Comment by martianzhang** [comment]
-report-type [markdown|html] will give a score of SQL, in other report-types soar doesn't give the score of SQL now.

**Comment by 90wukai** [comment]
@martianzhang why `-report-type text` show the score`100` ?
