### ISSUE TITLE
windows环境下，SOAR报错的问题

### ISSUE THREAD

**Issue by liipx** [XiaoMi/soar#4]
由于未对Windows环境进行适配，目前您可能无法在Windows环境中使用SOAR。

**Comment by martianzhang** [comment]
经过测试目前已知为使用第三方日志模块记录日志信息时使用了/dev/stderr做为输出时导致的异常。
后续会安排修复这个兼容性问题，多谢反馈。👍

**Comment by lgyers** [comment]
@martianzhang 
mac 可能用一个问题 
[soar.go:105] ioutil.ReadAll Error: read /dev/stdin: resource temporarily unavailable
