### ISSUE TITLE
Support real tests in CI

### ISSUE THREAD

**Issue by zhouzhuojie** [XiaoMi/soar#40]
It would be great if CI have real tests, not just `make fmt`.

https://github.com/XiaoMi/soar/blob/master/.travis.yml#L11

**Comment by martianzhang** [comment]
yeah，we will create a new branch for travis testing debug.

we do CI using locally command

make daily

**Comment by martianzhang** [comment]
after commit 6f2f562 .travis.yaml has included most of the CI things, but without linter check :(
