### ISSUE TITLE
SQL中包含1左边那个引号[`]，就会报错

### ISSUE THREAD

**Issue by figozhu** [XiaoMi/soar#45]
Please answer these questions before submitting your issue. Thanks!

1. What did you do?
```shell
./soar -query "SELECT f1 + f2 AS `total_num` FROM tb"
```

2. What did you expect to see?
能正常解析

3. What did you see instead?
```sql

SELECT  
  f1  + f2  AS  total_num  : command  not  found  
FROM  
  tb
```

## MySQL执行出错

syntax error at position 30 near ':'

4. What version of are you using (`soar -version`)?
Version: 2018-10-23 16:27:51 +0800 @7519019
Branch: master
Compile: 2018-10-23 18:26:17 +0800 by go version go1.10.4 linux/amd64
GitDirty: 105

**Comment by WithLin** [comment]
#33
