### ISSUE TITLE
安装步骤windows和Linux都报错。

### ISSUE THREAD

**Issue by vegetablebird-yeyz** [XiaoMi/soar#5]
如题，希望给出详细的ReadMe，3Q。

**Comment by vegetablebird-yeyz** [comment]
![default](https://user-images.githubusercontent.com/41948227/47256461-9347f080-d4b3-11e8-82c3-296ab7ce69ab.png)

**Comment by martianzhang** [comment]
报这个错误的原因是未配置GOPATH环境变量导致的。

可以先配置一下GOPATH再make。

这个问题的原因应该是高版本的go已经不是必须配置GOPATH导致的，我们考虑下这个问题的终极解决办法。

**Comment by liipx** [comment]
Go在1.8版本开始引入默认的GOPATH。
在不配置系统级的 GOPATH 变量的情况下，通过`go env GOPATH`命令 就可以获得GOPATH。

**Comment by martianzhang** [comment]
Go version large than 1.8 has default GOPATH.
use `go env GOPATH` get GOPATH envirment variable.

**Comment by martianzhang** [comment]
@vegetablebird-yeyz 50f8bf8 will fix this issue, please pull the lastest version and make a check.
