### ISSUE TITLE
zsh: exec format error: ./soar 我不是很確定這是否是bug?

### ISSUE THREAD

**Issue by wizarot** [XiaoMi/soar#50]
您好! 
   我在直接下載安裝,執行過程中,遇到以下問題. 但並不確定這是程序的問題或是我系統本身問題. 我在網上搜索,似乎很多軟件都遇到過同類情況.但沒有人給出本質原因和解決方案.

OSX
zsh 5.5 (x86_64-apple-darwin17.3.0)
我是用wget安裝 v0.8.1版本,然後按照文檔chmod 之後執行測試命令.
結果是zsh給我報了以下錯誤:

```
→ echo 'select * from film' | ./soar
zsh: exec format error: ./soar
```

嘗試直接運行,也會出現同樣的問題:
```
→ ./soar -m
zsh: exec format error: ./soar
```
如果這不是項目本身問題,也請回復一下我.
如果各位有人知道什麼原理,也請回復一下.

**Comment by martianzhang** [comment]
OSX suggest download [soar.darwin-amd64](https://github.com/XiaoMi/soar/releases/download/v0.8.1/soar.darwin-amd64).

**Comment by wizarot** [comment]
@martianzhang 
非常感谢,这个解决了问题.
It works!

**Comment by Super-H1** [comment]
nb❤️❤️❤️
