### ISSUE TITLE
soar需要create database的权限，对于RDS 这个权限太高，能不能兼容下。

### ISSUE THREAD

**Issue by ziyege** [XiaoMi/soar#59]
soar需要create database的权限
阿里云的RDS的最高权限账号  开了之后管理账号困难，而且这个账号权限太高，所以一般情况下的账号没有 create database的权限，请问能否考虑支持下。
非常感谢

**Comment by martianzhang** [comment]
关于数据库权限online-dsn需要相应库表的SELECT权限，test-dsn需要root最高权限。

test-dsn完全可以用非RDS的数据库，比如用docker起一个临时的实例。
