### ISSUE TITLE
咨询下慢日志使用工具pt-query-digest

### ISSUE THREAD

**Issue by xmabul** [XiaoMi/soar#62]
pt-query-digest是要自己下载吗，这个跟soar有什么关系？

**Comment by martianzhang** [comment]
`pt-query-digest`是percona公司出品的一款开源软件，和soar并没有直接的关系，因为朋友们经常使用所以在文档中也有提及，如果感觉不合适我们可以在文档中把它删掉。

详细使用方法见链接

https://www.percona.com/doc/percona-toolkit/LATEST/pt-query-digest.html

**Comment by xmabul** [comment]
> `pt-query-digest`是percona公司出品的一款开源软件，和soar并没有直接的关系，因为朋友们经常使用所以在文档中也有提及，如果感觉不合适我们可以在文档中把它删掉。
> 
> 详细使用方法见链接
> 
> https://www.percona.com/doc/percona-toolkit/LATEST/pt-query-digest.html

好的，谢谢
