### ISSUE TITLE
sql 语法检查卡死

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#74]
执行下面命令卡死：
soar.windows-amd64 -only-syntax-check true -query "select * from mysql;" -report-type markdown

执行下面命令正常：
soar.windows-amd64  -query "select * from mysql;" -report-type markdown -only-syntax-check true

**Comment by martianzhang** [comment]
这是golang命令行参数使用方式的问题，建议参考https://golang.org/pkg/flag/
```
-only-syntax-check true
```
如果中间不加等号与下面的是等价的
```
-only-syntax-check=true true
```
