### ISSUE TITLE
指定配置文件不生效

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#77]
./soar.exe -config='config/soar.yaml' -print-config  配置未生效
$ cat config/soar.yaml
test-dsn:
  addr: 127.0.0.1:3306
  schema: datatest
  user: root
  password: 123456
  disable: false
only-syntax-check: true
allow-online-as-test : true

./soar.exe -config='config/soar.yaml' -print-config -log-level=7
online-dsn:
  addr: ""
  schema: information_schema
  user: ""
  password: '********'
  charset: utf8mb4
  disable: true
test-dsn:
  addr: ""
  schema: ""
  user: ""
  password: '********'
  charset: ""
  disable: true
allow-online-as-test: false
drop-test-temporary: true
only-syntax-check: false
sampling-statistic-target: 100
sampling: false
profiling: false
trace: false
explain: true
......

**Comment by martianzhang** [comment]
8eafcf6c64fd402531d169bb0c247ad7fe543d2f fix this
