### ISSUE TITLE
建议sql语法检查时， 如果没有语法错误，增加提示信息， 目前返回为空

### ISSUE THREAD

**Issue by xiyangxixian** [XiaoMi/soar#78]

**Comment by martianzhang** [comment]
考虑到与IDE插件的兼容性，如果没有问题也显示类似"语法检查通过"的字样会让插件比较难兼容。
比如VS Code如果代码检查没问题，Problem/问题中显示为空。

目前可以通过`$?`返回值判断检查执行结果，为0表示通过。
