### ISSUE TITLE
文档写的太差了

### ISSUE THREAD

**Issue by hittanic** [XiaoMi/soar#82]
Issues on GitHub are intended to be related to bugs or feature requests, so we recommend using our other community resources instead of asking here.

- [SOAR Doc](http://github.com/XiaoMi/soar/blob/master/README.md)
- Any other questions can be asked in the community [![Gitter](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/xiaomi-dba/soar)

作为一个DBA， 我看了半天文档，不知道这工具怎么用， 文档写的太乱了

**Comment by martianzhang** [comment]
文档和使用上的建议可以在QQ群和gitter中反馈，我们一起来更新。

好的文档都是改出来的，不是么？
