### ISSUE TITLE
[Mac]ioutil.ReadAll Error: read /dev/stdin: resource temporarily unavailable

### ISSUE THREAD

**Issue by wanwaner** [XiaoMi/soar#86]
[soar.go:110] ioutil.ReadAll Error: read /dev/stdin: resource temporarily unavailable

**Comment by wanwaner** [comment]
[@localhost:~]$ soar -version
Version: 2018-11-05 14:02:42 +0800 @d070981
Branch: master
Compile: 2018-11-07 09:33:56 +0800 by go version go1.11.2 darwin/amd64
GitDirty: 15

[@localhost:~]$ soar
2018/11/07 14:30:16.845 [C] [soar.go:110] ioutil.ReadAll Error: read /dev/stdin: resource temporarily unavailable

**Comment by martianzhang** [comment]
经测试现在最新的版本的确有这个问题，应该是某次更新引入的。
在mac下可以复现, linux无法复现，定位原因后会进行修复。

**Comment by martianzhang** [comment]
new releae 0.10.0 fix this.
