### ISSUE TITLE
对于权限不够的检查,会卡死

### ISSUE THREAD

**Issue by wangmin19861205** [XiaoMi/soar#91]
2018/11/09 12:00:16.920 [W] [env.go:308] createDatabase, Error : Received #1044 error from MySQL server: "Access denied for user 'xxxx_all'@'%' to database 'optimizer_up2msgndl2tfxorl'"
2018/11/09 12:00:16.920 [E] [env.go:281] BuildVirtualEnv Error : Received #1044 error from MySQL server: "Access denied for user 'xxxx_all'@'%' to database 'optimizer_up2msgndl2tfxorl'"

权限不够时,会导致卡住,没有任何输出,建议优化下

**Comment by wangmin19861205** [comment]
发现貌似不是权限不够的问题,看log没有正常结束,这一块是不是可以加个超时时间,返个空啥的

**Comment by wangmin19861205** [comment]
这有个sql可以试试     
SELECT id,title,image_url,skip_type,skip_id,skip_name,content_type, (CASE WHEN NOW() <end_time THEN 2 ELSE 3 END) AS status FROM t_hot_activity WHERE begin_time < now() AND delete_flag=0 AND force_offline=0 AND end_time > now() AND ((user_type = 3 AND (corps='全部' OR FIND_IN_SET('123', corps)>0 ) )OR user_type=1) ORDER BY status asc,begin_time desc,skip_name LIMIT 0,5

**Comment by wangmin19861205** [comment]
发现是子查询、嵌套查询导致卡死,没有返回    建议加个超时时间之类的

**Comment by martianzhang** [comment]
@wangmin19861205 请提供一下导致HANG死的SQL，我们测试一下。

**Comment by wangmin19861205** [comment]
SELECT id,title,image_url,skip_type,skip_id,skip_name,content_type, (CASE WHEN NOW() <end_time THEN 2 ELSE 3 END) AS status FROM t_hot_activity WHERE begin_time < now() AND delete_flag=0 AND force_offline=0 AND end_time > now() AND ((user_type = 3 AND (corps='all' OR FIND_IN_SET('abc', corps)>0 ) )OR user_type=1) ORDER BY status asc,begin_time desc,skip_name LIMIT 0,5

**Comment by martianzhang** [comment]
as #126 said， we add privilege check in `-check-config`，before running SOAR, run `soar -config soar.yaml -check-config` command first.
