### ISSUE TITLE
soar: 未找到命令

### ISSUE THREAD

**Issue by ywc953** [XiaoMi/soar#92]
make过程中有些包显示获取超时，但build success，想试用命令显示soar命令未找到，请问是包没获取全的原因吗

**Comment by liipx** [comment]
soar的编译后的二进制文件是默认生成在项目根目录中的bin目录中的。请检查下该目录下有没有生成相应的二进制文件。另外最好能够再提供下操作系统版本以及make过程产生的日志信息，以便我们能够帮助你解决问题。
