### ISSUE TITLE
离线环境源码编译

### ISSUE THREAD

**Issue by ywc953** [XiaoMi/soar#94]
你好，由于项目关系需要在离线的环境中源码编译soar，请问是否可以先离线安装好各个依赖包，另外makefile中的依赖包都是需要的吗？

**Comment by martianzhang** [comment]
因为目前依赖的tidb中的parser库在调整，等tidb这边调整完了我们会把所有的依赖都打到vender中

**Comment by ywc953** [comment]
好的，谢谢

**Comment by martianzhang** [comment]
@yehangjun we have update `github.com/pingcap/parser`, now `soar` can be built with no other third-party source code dependency.
