### ISSUE TITLE
小米的手机真鸡巴烂

### ISSUE THREAD

**Issue by lyhabc** [XiaoMi/soar#95]
小米的手机真鸡巴烂， 彻底失望了，开源软件也这么烂，那个小米6x ，镜头突出来了，无话可说

**Comment by Dante-dan** [comment]
？？？

**Comment by NotFind** [comment]
你这话我就不爱听了。有本事自己写一个。哪儿烂了。用人家的东西。还在这bb。

**Comment by NotFind** [comment]
软件有问题，作者基本当天就修复了。

**Comment by Dante-dan** [comment]
这种人不适合用开源，开源靠的是大家一起维护。这属于巨婴
