### ISSUE TITLE
blacklist问题

### ISSUE THREAD

**Issue by liipx** [XiaoMi/soar#96]
1. blacklist文件识别路径是以binary所在的路径来计算相对路径的，相对路径应该以执行目录计算。
2. 在blacklist中使用SQL指纹时需要将?进行转义，否则soar会认为是正则表达式。

**Comment by martianzhang** [comment]
问题1在 5279b99274f336c9c45748167e325c0e5f76bc04 中fix了。
问题2 需要更新文档。

**Comment by martianzhang** [comment]
问题2在 5f5e5e69e64c1836d6766727b6e473f1ec07fe5f 中fix了
